export const TICKET_STATUS = {
  NEW: "NEW",
  AI_ACTIVE: "AI_ACTIVE",
  WAITING_CUSTOMER: "WAITING_CUSTOMER",
  HUMAN_REVIEW: "HUMAN_REVIEW",
  HUMAN_TAKEOVER: "HUMAN_TAKEOVER",
  PENDING_CLOSE_REVIEW: "PENDING_CLOSE_REVIEW",
  CLOSED: "CLOSED"
};

export const AI_STATE = {
  ACTIVE: "ACTIVE",
  PAUSED: "PAUSED",
  TAKEN_OVER: "TAKEN_OVER",
  DISABLED: "DISABLED"
};
